<a href="https://colab.research.google.com/github/ssook1222/bigdata-analysist-certificate/blob/master/bigdata-analysist-certificate/task2/airplane_experience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 패키지 다 때려박기

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
from sklearn.metrics import accuracy_score

### 데이터 불러오기

In [5]:
x_train = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/x_train.csv')
y_train = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/y_train.csv')
x_test = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/x_test.csv')
y_test = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/y_test.csv')

#### 데이터셋 분리하기

In [6]:
x_train_tr, x_train_ts, y_train_tr, y_train_ts = train_test_split(x_train, y_train, test_size = 0.33, random_state = 10)

### 데이터 전처리하기

In [7]:
display(x_train_tr)
display(y_train_tr)
display(x_train_ts)
display(y_train_ts)

,ID,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,id
23695,29771,Male,Loyal Customer,9,Personal Travel,Eco Plus,612,2,3,2,...,1,3,1,4,4,2,1,0,0.0,NaN
32320,40500,Male,disloyal Customer,21,Business travel,Eco,247,0,0,0,...,2,3,2,4,4,4,2,3,4.0,NaN
11230,14084,Female,Loyal Customer,38,Business travel,Eco,355,4,4,4,...,4,1,4,3,3,3,4,4,8.0,NaN
20029,25175,Male,Loyal Customer,38,Business travel,Eco,372,3,5,5,...,3,4,3,3,2,3,3,4,7.0,NaN
12590,15804,Male,Loyal Customer,75,Business travel,Eco Plus,236,2,2,2,...,3,4,2,4,3,4,3,6,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17904,22479,Female,Loyal Customer,32,Personal Travel,Eco,833,4,4,3,...,1,4,3,4,5,5,1,43,23.0,NaN
37597,47056,Male,Loyal Customer,53,Business travel,Business,2634,5,5,1,...,3,3,4,3,4,3,5,0,0.0,NaN
10201,12807,Male,Loyal Customer,65,Personal Travel,Eco,1589,2,4,2,...,4,3,2,5,4,5,4,0,0.0,NaN
9372,11774,Male,disloyal Customer,22,Business travel,Business,1162,0,0,0,...,5,5,4,5,5,5,5,1,0.0,NaN
50496,63159,Female,Loyal Customer,41,Personal Travel,Eco,283,3,5,3,...,3,5,3,5,4,4,3,0,3.0,NaN

          ID             satisfaction
23695  29771  neutral or dissatisfied
32320  40500                satisfied
11230  14084  neutral or dissatisfied
20029  25175  neutral or dissatisfied
12590  15804  neutral or dissatisfied
...      ...                      ...
17904  22479  neutral or dissatisfied
37597  47056                satisfied
10201  12807  neutral or dissatisfied
9372   11774                satisfied
50496  63159  neutral or dissatisfied

[55692 rows x 2 columns]

,ID,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,id
10478,13146,Male,Loyal Customer,51,Business travel,Business,150,1,1,1,...,5,5,5,4,4,5,3,0,0.0,NaN
36396,45547,Male,Loyal Customer,58,Business travel,Eco,278,2,5,5,...,2,2,3,1,2,1,2,9,9.0,NaN
53417,66877,Male,Loyal Customer,34,Personal Travel,Eco Plus,227,1,5,1,...,4,3,2,5,5,4,4,5,3.0,NaN
56629,70843,Female,Loyal Customer,20,Personal Travel,Eco,395,4,1,4,...,2,3,4,4,2,4,2,0,0.0,NaN
51795,64784,Female,Loyal Customer,30,Business travel,Eco,2400,1,3,3,...,1,3,2,3,1,1,1,0,11.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70456,88058,Male,Loyal Customer,60,Business travel,Eco,189,1,2,5,...,1,2,2,3,1,2,1,45,50.0,NaN
41013,51307,Male,Loyal Customer,49,Business travel,Business,837,3,3,3,...,4,4,4,4,3,4,3,25,17.0,NaN
46410,58057,Male,Loyal Customer,56,Personal Travel,Eco,157,3,2,0,...,4,3,2,4,1,3,4,0,0.0,NaN
62833,78554,Male,Loyal Customer,52,Business travel,Business,802,2,4,4,...,2,2,2,2,1,2,3,61,52.0,NaN
34319,42964,Female,Loyal Customer,47,Business travel,Business,370,2,2,2,...,4,4,4,4,5,4,4,19,12.0,NaN

          ID             satisfaction
10478  13146                satisfied
36396  45547  neutral or dissatisfied
53417  66877  neutral or dissatisfied
56629  70843                satisfied
51795  64784  neutral or dissatisfied
...      ...                      ...
70456  88058  neutral or dissatisfied
41013  51307                satisfied
46410  58057  neutral or dissatisfied
62833  78554  neutral or dissatisfied
34319  42964                satisfied

[27431 rows x 2 columns]

In [8]:
x_train_tr[x_train_tr.isna() == True].count()

ID                                   0
Gender                               0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Inflight service                     0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
id                                   0
dtype: int64

In [9]:
x_train_tr.isna().sum()

ID                                       0
Gender                                   0
Customer Type                            0
Age                                      0
Type of Travel                           0
Class                                    0
Flight Distance                          0
Inflight wifi service                    0
Departure/Arrival time convenient        0
Ease of Online booking                   0
Gate location                            0
Food and drink                           0
Online boarding                          0
Seat comfort                             0
Inflight entertainment                   0
On-board service                         0
Leg room service                         0
Baggage handling                         0
Checkin service                          0
Inflight service                         0
Cleanliness                              0
Departure Delay in Minutes               0
Arrival Delay in Minutes               175
id                                   55692
dtype: int64

결측치가 있는 열 제거

In [10]:
x_train_tr.columns

Index(['ID', 'Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'id'],
      dtype='object')

In [29]:
x_train_tr = x_train_tr[['ID', 'Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness']]

x_train_ts = x_train_ts[['ID', 'Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness']]

x_test = x_test[['ID', 'Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness']]

#### 라벨 인코딩

In [12]:
x_train_tr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 55692 entries, 23695 to 50496
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ID                                 55692 non-null  int64
 1   Gender                             55692 non-null  object
 2   Customer Type                      55692 non-null  object
 3   Age                                55692 non-null  int64
 4   Type of Travel                     55692 non-null  object
 5   Class                              55692 non-null  object
 6   Flight Distance                    55692 non-null  int64
 7   Inflight wifi service              55692 non-null  int64
 8   Departure/Arrival time convenient  55692 non-null  int64
 9   Ease of Online booking             55692 non-null  int64
 10  Gate location                      55692 non-null  int64
 11  Food and drink                     55692 non-null  int64
 12  Online boarding                    55692 non-null  int64
 13  Seat comfort                       55692 non-null  int64
 14  Inflight entertainment             55692 non-null  int64
 15  On-board service                   55692 non-null  int64
 16  Leg room service                   55692 non-null  int64
 17  Baggage handling                   55692 non-null  int64
 18  Checkin service                    55692 non-null  int64
 19  Inflight service                   55692 non-null  int64
 20  Cleanliness                        55692 non-null  int64
dtypes: int64(17), object(4)
memory usage: 9.3+ MB

In [13]:
le = LabelEncoder()

x_train_tr['Gender'] = le.fit_transform(x_train_tr['Gender'])
x_train_tr['Customer Type'] = le.fit_transform(x_train_tr['Customer Type'])
x_train_tr['Type of Travel'] = le.fit_transform(x_train_tr['Type of Travel'])
x_train_tr['Class'] = le.fit_transform(x_train_tr['Class'])

x_train_ts['Gender'] = le.fit_transform(x_train_ts['Gender'])
x_train_ts['Customer Type'] = le.fit_transform(x_train_ts['Customer Type'])
x_train_ts['Type of Travel'] = le.fit_transform(x_train_ts['Type of Travel'])
x_train_ts['Class'] = le.fit_transform(x_train_ts['Class'])

x_test['Gender'] = le.fit_transform(x_test['Gender'])
x_test['Customer Type'] = le.fit_transform(x_test['Customer Type'])
x_test['Type of Travel'] = le.fit_transform(x_test['Type of Travel'])
x_test['Class'] = le.fit_transform(x_test['Class'])

In [27]:
y_train_tr['satisfaction'] = le.fit_transform(y_train_tr['satisfaction'])
y_train_ts['satisfaction'] = le.fit_transform(y_train_ts['satisfaction'])
y_test['satisfaction'] = le.fit_transform(y_test['satisfaction'])

In [15]:
display(x_train_tr)
display(x_train_ts)

,ID,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness
23695,29771,1,0,9,1,2,612,2,3,2,...,1,2,1,1,3,1,4,4,2,1
32320,40500,1,1,21,0,1,247,0,0,0,...,2,0,2,2,3,2,4,4,4,2
11230,14084,0,0,38,0,1,355,4,4,4,...,4,4,4,4,1,4,3,3,3,4
20029,25175,1,0,38,0,1,372,3,5,5,...,3,3,3,3,4,3,3,2,3,3
12590,15804,1,0,75,0,2,236,2,2,2,...,3,2,3,3,4,2,4,3,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17904,22479,0,0,32,1,1,833,4,4,3,...,1,3,1,1,4,3,4,5,5,1
37597,47056,1,0,53,0,0,2634,5,5,1,...,4,4,4,3,3,4,3,4,3,5
10201,12807,1,0,65,1,1,1589,2,4,2,...,4,2,4,4,3,2,5,4,5,4
9372,11774,1,1,22,0,0,1162,0,0,0,...,5,0,4,5,5,4,5,5,5,5
50496,63159,0,0,41,1,1,283,3,5,3,...,3,3,3,3,5,3,5,4,4,3

,ID,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness
10478,13146,1,0,51,0,0,150,1,1,1,...,3,4,5,5,5,5,4,4,5,3
36396,45547,1,0,58,0,1,278,2,5,5,...,2,2,2,2,2,3,1,2,1,2
53417,66877,1,0,34,1,2,227,1,5,1,...,4,1,4,4,3,2,5,5,4,4
56629,70843,0,0,20,1,1,395,4,1,4,...,2,4,1,2,3,4,4,2,4,2
51795,64784,0,0,30,0,1,2400,1,3,3,...,1,1,1,1,3,2,3,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70456,88058,1,0,60,0,1,189,1,2,5,...,1,1,1,1,2,2,3,1,2,1
41013,51307,1,0,49,0,0,837,3,3,3,...,3,5,4,4,4,4,4,3,4,3
46410,58057,1,0,56,1,1,157,3,2,0,...,4,0,4,4,3,2,4,1,3,4
62833,78554,1,0,52,0,0,802,2,4,4,...,4,3,2,2,2,2,2,1,2,3
34319,42964,0,0,47,0,0,370,2,2,2,...,4,4,4,4,4,4,4,5,4,4

차이가 크게 나는 행이 있음. 정규화 진행 필요

#### Min-Max 정규화 진행

In [16]:
MinMax = MinMaxScaler()

In [17]:
x_train_tr_data = MinMax.fit_transform(x_train_tr)
x_train_ts_data = MinMax.fit_transform(x_train_ts)
x_test_data = MinMax.fit_transform(x_test)

x_train_tr = pd.DataFrame(columns = x_train_tr.columns, data = x_train_tr_data)
x_train_ts = pd.DataFrame(columns = x_train_ts.columns, data = x_train_ts_data)
x_test = pd.DataFrame(columns = x_test.columns, data = x_test_data)

### 데이터 모델링 진행

In [18]:
x_train_tr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55692 entries, 0 to 55691
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ID                                 55692 non-null  float64
 1   Gender                             55692 non-null  float64
 2   Customer Type                      55692 non-null  float64
 3   Age                                55692 non-null  float64
 4   Type of Travel                     55692 non-null  float64
 5   Class                              55692 non-null  float64
 6   Flight Distance                    55692 non-null  float64
 7   Inflight wifi service              55692 non-null  float64
 8   Departure/Arrival time convenient  55692 non-null  float64
 9   Ease of Online booking             55692 non-null  float64
 10  Gate location                      55692 non-null  float64
 11  Food and drink                     55692 non-null  float64
 12  Online boarding                    55692 non-null  float64
 13  Seat comfort                       55692 non-null  float64
 14  Inflight entertainment             55692 non-null  float64
 15  On-board service                   55692 non-null  float64
 16  Leg room service                   55692 non-null  float64
 17  Baggage handling                   55692 non-null  float64
 18  Checkin service                    55692 non-null  float64
 19  Inflight service                   55692 non-null  float64
 20  Cleanliness                        55692 non-null  float64
dtypes: float64(21)
memory usage: 8.9 MB

In [19]:
rfc = RandomForestClassifier()

In [20]:
x_train_tr = x_train_tr[:1000]
y_train_tr = y_train_tr[:1000]

In [31]:
x_test = x_test[:1000]

In [21]:
model = rfc.fit(x_train_tr, y_train_tr)

In [32]:
predict1 = model.predict(x_train_ts)
predict2 = model.predict(x_test)

In [44]:
y_test = y_test[:1000]
predict1 = predict1[:1000]

In [38]:
y_test

       ID  satisfaction
0       1             0
1      16             0
2      17             0
3      25             0
4      27             1
..    ...           ...
995  4841             0
996  4846             0
997  4852             0
998  4863             0
999  4864             0

[1000 rows x 2 columns]

In [45]:
print(accuracy_score(predict1[:,1], y_test['satisfaction']))

0.519

### 제출하기

In [47]:
predict2

array([[27651,     0],
       [ 2309,     0],
       [  546,     0],
       ...,
       [23866,     0],
       [73915,     0],
       [14084,     0]])

In [48]:
def satisfact(x):
  if x == 0:
    return 'neutral or dissatisfied'
  else:
    return 'satisfied'

In [51]:
submit = pd.DataFrame({'ID':y_test['ID'], 'satisfaction':predict2[:,1]})

In [54]:
submit['satisfaction'] = submit.satisfaction.apply(lambda x:satisfact(x))

In [55]:
submit.to_csv('result.csv')

In [56]:
submit.head(5)

   ID             satisfaction
0   1  neutral or dissatisfied
1  16  neutral or dissatisfied
2  17  neutral or dissatisfied
3  25  neutral or dissatisfied
4  27  neutral or dissatisfied