<a href="https://colab.research.google.com/github/ssook1222/bigdata-analysist-certificate/blob/master/bigdata-analysist-certificate/first/task2/student_predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 학생성적 예측 데이터

### 패키지 다 때려박기

In [1]:
import pandas as pd
import numpy as np

In [10]:
from sklearn.preprocessing import LabelEncoder

In [24]:
from sklearn.tree import DecisionTreeRegressor

#### 회귀 모델은 아래와 같은 걸로 평가 지표 사용

In [43]:
from sklearn.metrics import mean_absolute_error

### 데이터 불러오기

In [2]:
x_train = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/studentscore/X_train.csv')
x_test = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/studentscore/X_test.csv')
y_train = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/studentscore/y_train.csv')
y_test = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/studentscore/y_test.csv')

### 데이터 전처리

#### 데이터 프레임 확인

In [3]:
display(x_train)
display(x_test)

,StudentID,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,...,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2
0,1714,GP,F,18,U,GT3,T,4,3,other,...,no,4,3,3,1,1,3,0,14,13
1,1254,GP,F,17,U,GT3,T,4,3,health,...,yes,4,4,3,1,3,4,0,13,15
2,1639,GP,F,16,R,GT3,T,4,4,health,...,no,2,4,4,2,3,4,6,10,11
3,1118,GP,M,16,U,GT3,T,4,4,services,...,no,5,3,3,1,3,5,0,15,13
4,1499,GP,M,19,U,GT3,T,3,2,services,...,yes,4,5,4,1,1,4,0,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
673,1074,GP,M,15,U,GT3,T,4,4,services,...,no,5,3,3,1,1,5,4,10,13
674,1044,GP,M,15,R,GT3,T,4,4,other,...,yes,1,3,5,3,5,1,8,12,10
675,1078,GP,M,17,U,LE3,T,4,4,other,...,no,4,1,1,2,2,5,0,12,13
676,1055,MS,M,17,R,GT3,T,1,1,other,...,yes,4,5,5,1,3,2,0,10,9
677,1394,GP,F,17,U,GT3,T,3,2,health,...,no,5,2,2,1,2,5,0,18,18

,StudentID,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,...,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2
0,1000,GP,F,16,U,GT3,T,4,2,services,...,no,4,2,3,1,1,5,2,15,16
1,1008,GP,M,19,U,GT3,T,1,2,other,...,no,4,5,2,2,2,4,3,13,11
2,1013,GP,F,16,U,GT3,T,4,4,services,...,no,3,2,3,1,2,2,6,13,14
3,1014,GP,F,16,U,GT3,T,3,1,services,...,no,4,3,3,1,2,5,4,7,7
4,1017,GP,F,15,U,LE3,A,3,4,other,...,yes,5,3,2,1,1,1,0,10,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,2032,GP,F,15,R,LE3,T,3,1,other,...,no,4,4,2,2,3,3,6,15,15
362,2034,GP,M,17,U,GT3,T,3,3,services,...,yes,4,3,4,2,3,4,12,12,12
363,2035,GP,F,16,U,GT3,T,2,3,services,...,no,2,3,1,1,1,3,2,16,16
364,2036,MS,F,16,U,GT3,T,3,1,other,...,no,3,1,3,1,3,1,0,8,6
365,2037,MS,M,18,U,GT3,T,4,4,teacher,...,no,3,2,4,1,4,2,4,15,14

#### 결측치 확인

In [8]:
print(x_train.isna().sum())
print(x_test.isna().sum())

StudentID     0
school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
dtype: int64
StudentID     0
school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
dtype: int64

둘 다 없음. ML을 위한 인코딩 진행

In [9]:
print(x_train.info())
print(x_test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 678 entries, 0 to 677
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   678 non-null    int64
 1   school      678 non-null    object
 2   sex         678 non-null    object
 3   age         678 non-null    int64
 4   address     678 non-null    object
 5   famsize     678 non-null    object
 6   Pstatus     678 non-null    object
 7   Medu        678 non-null    int64
 8   Fedu        678 non-null    int64
 9   Mjob        678 non-null    object
 10  Fjob        678 non-null    object
 11  reason      678 non-null    object
 12  guardian    678 non-null    object
 13  traveltime  678 non-null    int64
 14  studytime   678 non-null    int64
 15  failures    678 non-null    int64
 16  schoolsup   678 non-null    object
 17  famsup      678 non-null    object
 18  paid        678 non-null    object
 19  activities  678 non-null    object
 20  nursery     678 non-null    object
 21  higher      678 non-null    object
 22  internet    678 non-null    object
 23  romantic    678 non-null    object
 24  famrel      678 non-null    int64
 25  freetime    678 non-null    int64
 26  goout       678 non-null    int64
 27  Dalc        678 non-null    int64
 28  Walc        678 non-null    int64
 29  health      678 non-null    int64
 30  absences    678 non-null    int64
 31  G1          678 non-null    int64
 32  G2          678 non-null    int64
dtypes: int64(16), object(17)
memory usage: 174.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   366 non-null    int64
 1   school      366 non-null    object
 2   sex         366 non-null    object
 3   age         366 non-null    int64
 4   address     366 non-null    object
 5   famsize     366 non-null    object
 6   Pstatus     366 non-null    object
 7   Medu        366 non-null    int64
 8   Fedu        366 non-null    int64
 9   Mjob        366 non-null    object
 10  Fjob        366 non-null    object
 11  reason      366 non-null    object
 12  guardian    366 non-null    object
 13  traveltime  366 non-null    int64
 14  studytime   366 non-null    int64
 15  failures    366 non-null    int64
 16  schoolsup   366 non-null    object
 17  famsup      366 non-null    object
 18  paid        366 non-null    object
 19  activities  366 non-null    object
 20  nursery     366 non-null    object
 21  higher      366 non-null    object
 22  internet    366 non-null    object
 23  romantic    366 non-null    object
 24  famrel      366 non-null    int64
 25  freetime    366 non-null    int64
 26  goout       366 non-null    int64
 27  Dalc        366 non-null    int64
 28  Walc        366 non-null    int64
 29  health      366 non-null    int64
 30  absences    366 non-null    int64
 31  G1          366 non-null    int64
 32  G2          366 non-null    int64
dtypes: int64(16), object(17)
memory usage: 94.5+ KB
None

#### 라벨 인코딩 진행

In [11]:
le = LabelEncoder()

In [16]:
columns = x_train.select_dtypes(exclude = [np.int64, np.float64]).columns

In [19]:
for column in columns:
  x_train[column] = le.fit_transform(x_train[column])
  x_test[column] = le.fit_transform(x_test[column])

#### 필요없는 칼럼 제거

In [23]:
x_train = x_train[['school', 'sex', 'age', 'address', 'famsize', 'Pstatus',
       'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime',
       'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime',
       'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2']]

x_test = x_test[['school', 'sex', 'age', 'address', 'famsize', 'Pstatus',
       'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime',
       'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime',
       'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2']]

### 모델링 진행

In [25]:
dcr = DecisionTreeRegressor()

In [26]:
model = dcr.fit(x_train, y_train)

In [28]:
predict = model.predict(x_test)

In [ ]:
predict

In [40]:
y_test

     StudentID  G3
0         1000  16
1         1008  11
2         1013  14
3         1014   6
4         1017  11
..         ...  ..
361       2032  15
362       2034  11
363       2035  17
364       2036   8
365       2037  14

[366 rows x 2 columns]

In [42]:
predict[:,1]

array([14. , 13. , 14. ,  7. , 12. , 18. , 17. , 14. , 11. , 13. , 17. ,
       10. , 12. , 13. , 14. ,  8. , 11. , 16. ,  9. , 10. , 12. , 10. ,
       16. , 10. ,  9. , 11. , 10. , 10. , 11. , 17. ,  8. , 14. , 12. ,
       12. , 10. , 10. ,  6. , 17. , 11. ,  8. , 12. , 14. , 14. , 15. ,
        0. , 11. , 13. ,  0. , 11. , 12. , 11. ,  8. , 16. , 15. ,  8. ,
        8. , 17. ,  8. , 18. , 13. ,  9. , 15. , 11. , 14. ,  6. , 10. ,
        9. , 14. , 15. , 17. ,  7. , 11. ,  9. , 10. , 12. , 11. ,  0. ,
       12. ,  9. , 11. , 14. , 13. , 10. , 14. , 11. , 11. , 11. , 16. ,
       16. , 12. , 13. , 15. ,  0. , 11. , 10. , 18. , 13. , 16. ,  0. ,
        9. , 14. , 14. , 10. , 15.5, 11. ,  8. , 11. , 13. , 12. , 10. ,
       10. , 11. , 14. , 11. , 10. , 14. , 15. , 11. , 12. , 10. , 12. ,
       18. ,  0. , 10. , 13. , 13. , 14. , 12. , 11. , 14. , 13. , 12. ,
        8. ,  7. , 13. , 12. , 12. ,  9. , 17. , 12. , 11. , 14. , 16. ,
       15. , 13. , 13. , 11. , 15. , 18. ,  0. , 14. ,  0. , 11. , 10. ,
       10. , 10. ,  8. , 10. , 15. , 11. ,  7. , 14. , 10. , 11. , 15. ,
       13. , 12. , 16. ,  0. , 10. , 10. , 10. , 14. , 13. , 14. ,  6. ,
       11. , 12. ,  7. , 11. ,  9. , 13. , 13. ,  8. , 11. , 10. , 10. ,
       10. ,  0. ,  9. , 13. , 15. , 17. , 12. , 10. , 11. , 14. ,  6. ,
       12. , 14. , 14. ,  9. , 11. , 10. , 11. , 13. ,  8. , 10. , 11. ,
       14. , 13. , 11. , 11. , 10. , 16. , 12. ,  8. , 15. , 17. ,  8. ,
       16. , 14. , 10. ,  0. ,  7. , 16. , 10. , 18. , 14. , 11. , 10. ,
       15. , 20. ,  5. , 11. , 14. , 10. ,  8. , 16. , 11. , 17. , 10. ,
       10. , 12. ,  9. , 13. , 14. , 10. , 15. ,  0. , 10. , 14. , 16. ,
       12. , 12. , 11. ,  0. , 14. , 14. ,  8. , 18. , 15. , 14. , 10. ,
       11. , 11. , 13. , 10. ,  9. ,  9. , 17. , 10. , 15. ,  8. , 10. ,
        7. , 13. ,  0. , 14. , 14. , 14. , 14. , 17. ,  0. , 13. ,  6. ,
       14. ,  4. ,  8. , 13. , 11. , 10. , 15. , 13. , 18. , 11. , 12. ,
       11. ,  8. ,  8. , 16. , 16. ,  6. , 13. , 15. ,  4. , 13. , 14. ,
       12. , 10. , 13. , 14. , 14. , 11. , 10. , 10. , 12. ,  8. , 13. ,
       11. , 15. , 16. , 14. , 11. , 16. , 15. , 14. , 13. , 15. , 12. ,
       12. , 11. , 11. , 10. ,  9. ,  0. ,  9. , 10. ,  8. ,  0. , 14. ,
        0. , 13. , 13. , 18. , 10. , 13. ,  0. ,  9. ,  8. , 15. ,  8. ,
        8. , 11. , 11. , 16. , 11. , 12. , 12. ,  0. , 10. , 16. , 12. ,
       14. , 10. , 19. ])

In [45]:
print(mean_absolute_error(predict[:,1], y_test['G3']))

1.9057377049180328

### 제출하기

In [46]:
submit = pd.DataFrame(data = predict, columns = y_test.columns)

In [47]:
submit.head(5)

   StudentID    G3
0     1199.0  14.0
1     1613.0  13.0
2     1676.0  14.0
3     1328.0   7.0
4     2033.0  12.0

In [48]:
submit.to_csv('result.csv')